import { CnaesModel } from './cnaes.model';
import { QsaModel } from './qsa.model';

export class CnpjResponseModel {
  uf: string;
  cep: string;
  qsa: QsaModel[];
  cnpj: string;
  pais: string | null;
  email: string | null;
  porte: string;
  bairro: string;
  numero: string;
  ddd_fax: string;
  municipio: string;
  logradouro: string;
  cnae_fiscal: number;
  codigo_pais: number | null;
  complemento: string;
  codigo_porte: number;
  razao_social: string;
  nome_fantasia: string;
  capital_social: number;
  ddd_telefone_1: string;
  ddd_telefone_2: string;
  opcao_pelo_mei: string | null;
  descricao_porte: string;
  codigo_municipio: number;
  cnaes_secundarios: CnaesModel[];
  natureza_juridica: string;
  situacao_especial: string;
  opcao_pelo_simples: null;
  situacao_cadastral: number;
  data_opcao_pelo_mei: null;
  data_exclusao_do_mei: null;
  cnae_fiscal_descricao: string;
  codigo_municipio_ibge: number;
  data_inicio_atividade: string;
  data_situacao_especial: null;
  data_opcao_pelo_simples: null;
  data_situacao_cadastral: string;
  nome_cidade_no_exterior: string;
  codigo_natureza_juridica: number;
  data_exclusao_do_simples: null;
  motivo_situacao_cadastral: number;
  ente_federativo_responsavel: string;
  identificador_matriz_filial: number;
  qualificacao_do_responsavel: number;
  descricao_situacao_cadastral: string;
  descricao_tipo_de_logradouro: string;
  descricao_motivo_situacao_cadastral: string;
  descricao_identificador_matriz_filial: string;
}
