# Docs: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Testes

on: pull_request

jobs:
  continuos-integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: bash scripts/test.sh

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
