name: Tests

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  test:
    runs-on: ansible
    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js memory limit
        env:
          NODE_OPTIONS: --max-old-space-size=4096

      - name: Use Node.js 20.5.1
        uses: actions/setup-node@v3
        with:
          node-version: 20.5.1

      - run: |
          npm install --if-present

      - run: |
          npx prisma generate

      - run: |
          npm run test --if-present

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
